### PR TITLE
New rails project setup

### PR DESCRIPTION
**Pull request by dcox**
Hi @eliotsykes , will you please review my new project setup?

### CODE REVIEW

**Comment by dcox** [comment]
@eliotsykes upgraded. Thank you!

**Comment by eliotsykes** [comment]
Good work on those last 2 commits especially as they are well-defined and with excellent commit messages :+1:

**Comment by dcox** [comment]
Thanks @eliotsykes ! 

Is it OK for me to merge this branch since you gave me a :+1: ?

**Comment by eliotsykes** [comment]
@dcox Yep please do merge - see the Bloc message I sent a little earlier about merging PRs when you need to.

**Pull request merged**
